name: Build and deploy Jekyll site

on:
  push:
    branches: [master]

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Jekyll site
        uses: helaili/jekyll-action@v2
        with:
          target_branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: .
